
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/bitrise-steplib/bitrise-step-android-unit-test"
  version = "0.9.5"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-tools/go-android"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-tools/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/kballard/go-shellquote"

[prune]
  go-tests = true
  unused-packages = true
